spring:
  application:
    name: jun-ai
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jun_ai
    username: root
    password: root
server:
  port: 8110
  servlet:
    context-path: /api
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.jun.junai.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

